"""initial

Revision ID: 55abfa8a7d16
Revises: ef583a94bd2f
Create Date: 2020-05-10 22:05:02.186376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55abfa8a7d16'
down_revision = 'ef583a94bd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogcount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('click', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogcount')
    # ### end Alembic commands ###
